// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace MyMlAppML.Model
{
    public class ModelInput
    {
        [ColumnName("Emotion"), LoadColumn(0)]
        public string Emotion { get; set; }


        [ColumnName("Date"), LoadColumn(1)]
        public string Date { get; set; }


        [ColumnName("UserName"), LoadColumn(2)]
        public string UserName { get; set; }


        [ColumnName("Tweet"), LoadColumn(3)]
        public string Tweet { get; set; }


    }
}
